### ISSUE TITLE
googleapis.admin.directory_v1 - Missing request parameter?

### ISSUE THREAD

**Issue by goranj** [dart-lang/googleapis#9] opened 2016-04-16 17:25 UTC
Can't find a "fields" parameter (for partial response) in the UsersResourceApi methods.

**Comment by mkustermann** [comment] 2017-03-29 09:52
The discovery generator currently does not support the general request parameters.

Marking as duplicate of [dart-lang/discoveryapis_generator/issues/123](https://github.com/dart-lang/discoveryapis_generator/issues/123).

**Closed by mkustermann** 2017-03-29 09:52 UTC
