### ISSUE TITLE
Add an option – somewhere – to disable request header setting

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/googleapis#5] opened 2015-06-02 22:36 UTC
![screen shot 2015-06-02 at 3 35 50 pm](https://cloud.githubusercontent.com/assets/17034/7948873/13b18c90-093d-11e5-8f96-65085172b24d.png)

I'm seeing a lot of these browser errors

**Comment by kevmoo** [comment] 2015-06-02 22:38
Or at least disable setting of "unsafe" headers

**Comment by mkustermann** [comment] 2017-03-29 10:10
This is a duplicate of [dart-lang/discoveryapis_generator/issues/170](https://github.com/dart-lang/discoveryapis_generator/issues/170).

The workaround for now is to wrap the `http.Client` and remove the headers.

**Closed by mkustermann** 2017-03-29 10:10 UTC
